spring:
  profiles:
    active: cloud
---

spring:
  profiles: cloud
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: https://github.com/mescanef/dromader-configs
server:
  port: 10000
sidecar:
  port: 8000
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    hostname: api-gateway
    nonSecurePort: 80
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

---

spring:
  profiles: development
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mescanef/dromader-configs
server:
  port: 10000
sidecar:
  port: 8000
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
