spring:
  profiles:
    active: cloud
---

spring:
  profiles: cloud
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: https://github.com/mescanef/dromader-configs
        health:
          repositories:
            movie:
              label: master
            rating:
              label: master
server:
  port: 8888
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    hostname: localhost
    nonSecurePort: 80
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost/eureka

---

spring:
  profiles: development
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mescanef/dromader-configs
        health:
          repositories:
            movie:
              label: master
server:
  port: 8888
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    hostname: configserver
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://locahost:8761/eureka/
